- name: Set hostname
  hostname:
    name: "{{ var_name }}-{{ dev_environment}}-host"

- name: Copy SSH config file with
  template:
    src: config.toml.j2
    dest: /home/{{ item }}/.ssh/config
    owner: ec2-user
    group: ec2-user
    mode: '0644'
  with_items:
    - mstojanovic
    - mistojanovic
    - miistojanovic

- name: Copy PEM key to ec2-user home directory
  copy:
    src: files/{{ var_name}}_{{ peering_environment }}.pem
    dest: /home/{{ item }}/.ssh/{{ var_name }}_{{ peering_environment }}.pem
    owner: ec2-user
    group: ec2-user
    mode: '0400'
  with_items:
    - mstojanovic
    - mistojanovic
    - miistojanovic